// <auto-generated />
using System;
using Calendar.Services.ExtensionsAPI.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Calendar.Services.ExtensionsAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220304124740_TablesUpdate")]
    partial class TablesUpdate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Calendar.Services.ExtensionsAPI.Models.Example", b =>
                {
                    b.Property<int>("ExampleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExampleId"), 1L, 1);

                    b.Property<DateTime>("ExampleDateTime")
                        .HasColumnType("datetime2");

                    b.Property<double>("ExampleDouble")
                        .HasColumnType("float");

                    b.Property<string>("ExampleImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExampleInt")
                        .HasColumnType("int");

                    b.Property<string>("ExampleString")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ExampleId");

                    b.ToTable("Examples");
                });
#pragma warning restore 612, 618
        }
    }
}
